export const SEARCH_TRANSLATIONS = {
  '통합 검색': 'Search',
  통합검색: 'Search',
  '검색어를 두글자 이상 입력해주세요': 'Please enter at least two characters.',
  '검색 결과가 존재하지 않습니다': 'No search results found.',
  '결과 더보기': 'More results',
  소개: 'About',
  소식: 'News',
  구성원: 'Members',
  연구·교육: 'Research & Education',
  입학: 'Admissions',
  '학사 및 교과': 'Academics',
  공지사항: 'Notices',
  '새 소식': 'News',
  세미나: 'Seminars',
  교수진: 'Faculty',
  행정직원: 'Staff',
  전체: 'All',
  '학부 소개': 'About',
  연구: 'Research',
  학부: 'Undergraduate',
  대학원: 'Graduate',
  International: 'International',
  '수시 모집': 'Early Admission',
  '정시 모집': 'Regular Admission',
  '전기/후기 모집': 'Graduate Admission',
  Undergraduate: 'Undergraduate',
  Graduate: 'Graduate',
  'Exchange/Visiting Program': 'Exchange/Visiting Program',
  Scholarships: 'Scholarships',
  연구실: 'Labs',
  연구센터: 'Research Centers',
  연구그룹: 'Research Groups',
  'Top Conference List': 'Top Conference List',
};
